In [3]:
import pandas as pd
import numpy as np

In [26]:
df = pd.read_csv('./../features/FINAL_TEST.csv')

In [27]:
df

,index,n_v_pron,pron_n_v,adp_pron_n,adp_art_n,v_pron_n,n_adv_v,n_adp_n,art_n_v,adv_v_pron,...,om,nu,wel,ons,haten,deze,wat,dit,bij,auteurs
0,19437,0.015873,0.019841,0.003968,0.019841,0.011905,0.003968,0.023810,0.011905,0.007937,...,0.024590,0.008197,0.008197,NaN,0.008197,NaN,NaN,0.008197,NaN,Jan van der Veen
1,118464,0.019231,0.012238,0.020979,0.012238,0.006993,0.006993,0.010490,0.005245,0.008741,...,0.003185,0.006369,0.006369,NaN,0.003185,0.003185,0.006369,0.003185,0.006369,Willem Sluiter
2,36216,NaN,0.017391,0.030435,NaN,0.004348,0.013043,0.013043,NaN,0.013043,...,NaN,0.014599,0.007299,NaN,0.007299,0.021898,NaN,0.014599,0.014599,Joannes Mys
3,180196,NaN,0.004405,0.013216,0.017621,0.013216,0.013216,0.008811,0.008811,0.004405,...,NaN,NaN,0.008850,NaN,NaN,0.017699,0.008850,0.008850,0.008850,Joannes Vollenhove
4,182537,NaN,NaN,NaN,NaN,NaN,NaN,0.012048,0.012048,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hendrik Riemsnijder
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1228,113714,0.018692,0.004673,0.009346,0.018692,0.004673,0.014019,0.018692,0.004673,0.014019,...,NaN,0.018692,NaN,NaN,NaN,NaN,0.018692,NaN,NaN,Guilielmus Bolognino
1229,20509,0.030717,0.010239,0.013652,0.010239,0.027304,0.003413,0.010239,0.013652,0.006826,...,NaN,0.007042,NaN,NaN,NaN,NaN,NaN,0.007042,NaN,C. J. Wits
1230,191469,0.016667,0.016667,0.050000,0.016667,0.016667,0.016667,NaN,NaN,0.016667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jacob Westerbaen
1231,36610,0.008772,0.021930,0.021930,0.013158,0.008772,NaN,0.008772,0.013158,0.008772,...,0.015504,NaN,0.007752,NaN,0.007752,NaN,NaN,0.007752,NaN,Lucas van Mechelen
1232,5135,0.020794,0.015123,0.007561,0.007561,0.015123,0.005671,0.018904,0.011342,0.009452,...,0.004329,0.008658,NaN,NaN,NaN,NaN,NaN,0.004329,0.004329,Wilhelmus

In [29]:
dfWil = df.loc[1232]
dfWil

index               5135
n_v_pron        0.020794
pron_n_v       0.0151229
adp_pron_n    0.00756144
adp_art_n     0.00756144
                 ...
deze                 NaN
wat                  NaN
dit             0.004329
bij             0.004329
auteurs        Wilhelmus
Name: 1232, Length: 150, dtype: object

In [30]:
dfWil = dfWil[1:149]
dfWil

n_v_pron        0.020794
pron_n_v       0.0151229
adp_pron_n    0.00756144
adp_art_n     0.00756144
v_pron_n       0.0151229
                 ...
haten                NaN
deze                 NaN
wat                  NaN
dit             0.004329
bij             0.004329
Name: 1232, Length: 148, dtype: object

In [31]:
dfWil = dfWil.astype(float)

In [32]:
dfWil

n_v_pron      0.020794
pron_n_v      0.015123
adp_pron_n    0.007561
adp_art_n     0.007561
v_pron_n      0.015123
                ...
haten              NaN
deze               NaN
wat                NaN
dit           0.004329
bij           0.004329
Name: 1232, Length: 148, dtype: float64

In [35]:
dfWil.to_csv("FeaturesWilhelmus.csv")